### ISSUE TITLE
Remove unkown IPs from the endpoint

### ISSUE THREAD

**Issue by vpnachev** [gardener/aws-lb-readvertiser#15]
**What would you like to be added**:
The kubernetes endpoint sometimes is configured with outdated or manually added IPs which are not serving the kube-apiserver of the shoot. Because of this, applications deployed in the clusters are sporadically failing to connect to the kube-apiserver if they hit the wrong IP.

The readvertiser observes this behavior, but it only ensures that the currently active IPs are injected into the endpoint. 
```
time="2020-11-06T12:49:02Z" level=info msg="DNS lookup results are: [10.10.10.10 10.10.10.11]"
time="2020-11-06T12:49:02Z" level=info msg="Kubernetes Endpoint IPs : [\"10.20.20.20\" \"10.10.10.10\" \"10.10.10.11\" \"10.20.20.21\" \"10.20.20.22\" \"10.20.20.22\"]"
time="2020-11-06T12:49:02Z" level=info msg="Nothing to be done"
```

**Why is this needed**:
To ensure that the in-cluster applications are always routed to the API server of the cluster.

**Comment by BeckerMax** [comment]
Current assumption is that the readvertiser picks up changes of the ips behind the AWS LB but it only adds the new ips while not removing the old ones.
